# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bd27e01e412190eac186cd97d141bb729eda6c9246a5b7b3ef205997814c4555be3fa4809e0755d4342d589bc87befe833b8ebcba6653ff8f5d4692331a20cb

test:
  secret_key_base: 2d83f1e78ea6806ef98f3767a1ab78ff77746d95ac2ab48f77a71d835998d2b422897a9d268d3bdad2adcfda6f056e1cbddc262d634a86622b928184e6fa0f36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
